#!/usr/bin/env python3
"""Pull CCF Deadlines YAML and write the lab's filtered _data/conferences.yml."""

from __future__ import annotations

import datetime as dt
import json
import os
import subprocess
import sys
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML is required. Install with: pip install pyyaml\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "_data" / "conference_catalog.yml"
OUTPUT_PATH = ROOT / "_data" / "conferences.yml"
CCFDDL_URL = "https://ccfddl.github.io/conference/allconf.yml"


def stringify(value):
    if value is None:
        return None
    if isinstance(value, dt.datetime):
        return value.strftime("%Y-%m-%d %H:%M:%S")
    return str(value)


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def fetch_ccfddl():
    local_path = os.environ.get("CCFDDL_PATH")
    if local_path:
        raw = Path(local_path).read_text(encoding="utf-8")
    else:
        url = os.environ.get("CCFDDL_URL", CCFDDL_URL)
        try:
            request = urllib.request.Request(
                url,
                headers={"User-Agent": "cnu-ants-conference-sync/1.0"},
            )
            with urllib.request.urlopen(request, timeout=60) as response:
                raw = response.read().decode("utf-8")
        except Exception:
            raw = subprocess.check_output(
                ["curl", "-fsSL", url],
                text=True,
                timeout=60,
            )
    data = yaml.safe_load(raw)
    if not isinstance(data, list):
        raise RuntimeError("Unexpected CCF Deadlines format: expected a list")
    return data


def find_entry(allconf, catalog_item):
    title = str(
        catalog_item.get("ccfddl_title") or catalog_item["title"]
    ).lower()
    sub = catalog_item.get("ccfddl_sub")
    matches = [
        item
        for item in allconf
        if str(item.get("title", "")).lower() == title
    ]
    if sub:
        matches = [item for item in matches if item.get("sub") == sub]
    if not matches:
        return None
    return matches[0]


def timeline_entries(conf_year):
    rows = []
    for item in conf_year.get("timeline") or []:
        deadline = stringify(item.get("deadline"))
        if not deadline:
            continue
        rows.append(
            {
                "deadline": deadline,
                "abstract_deadline": stringify(item.get("abstract_deadline")),
                "comment": item.get("comment") or None,
            }
        )
    return rows


def build_editions(catalog, allconf):
    editions = []
    missing = []

    for item in catalog.get("conferences") or []:
        source = find_entry(allconf, item)
        if source is None:
            missing.append(item["title"])
            continue

        rank = source.get("rank") or {}
        for conf_year in source.get("confs") or []:
            deadlines = timeline_entries(conf_year)
            if not deadlines:
                continue
            editions.append(
                {
                    "title": item["title"],
                    "year": conf_year.get("year"),
                    "id": conf_year.get("id"),
                    "description": source.get("description"),
                    "tags": item.get("tags") or [],
                    "kiise": item.get("kiise"),
                    "bk21_if": item.get("bk21_if"),
                    "core": rank.get("core"),
                    "link": conf_year.get("link"),
                    "date": conf_year.get("date"),
                    "place": conf_year.get("place"),
                    "timezone": conf_year.get("timezone") or "AoE",
                    "deadlines": deadlines,
                }
            )

    editions.sort(key=lambda row: (str(row["title"]), row.get("year") or 0))
    return editions, missing


class NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def dump_yaml(data, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Generated by scripts/sync_deadlines.py. Do not edit by hand.\n")
        yaml.dump(
            data,
            handle,
            Dumper=NoAliasDumper,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False,
            width=88,
        )


def main():
    catalog = load_yaml(CATALOG_PATH)
    allconf = fetch_ccfddl()
    editions, missing = build_editions(catalog, allconf)

    if OUTPUT_PATH.exists():
        existing = load_yaml(OUTPUT_PATH) or {}
        if json.dumps(existing.get("editions"), sort_keys=True, default=str) == json.dumps(
            editions, sort_keys=True, default=str
        ) and existing.get("missing") == missing:
            print(
                json.dumps(
                    {
                        "changed": False,
                        "editions": len(editions),
                        "path": str(OUTPUT_PATH.relative_to(ROOT)),
                    },
                    ensure_ascii=False,
                )
            )
            return

    payload = {
        "source": CCFDDL_URL,
        "updated_at": dt.datetime.now(dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "missing": missing,
        "editions": editions,
    }
    dump_yaml(payload, OUTPUT_PATH)

    print(
        json.dumps(
            {
                "changed": True,
                "editions": len(editions),
                "missing": missing,
                "path": str(OUTPUT_PATH.relative_to(ROOT)),
            },
            ensure_ascii=False,
        )
    )
    if missing:
        sys.stderr.write(
            "Warning: not found in CCF Deadlines: " + ", ".join(missing) + "\n"
        )


if __name__ == "__main__":
    main()
