#!/usr/bin/env python3
"""Pull OpenAlex source metrics into _data/journals.yml."""

from __future__ import annotations

import datetime as dt
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML is required. Install with: pip install pyyaml\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "_data" / "journal_catalog.yml"
OUTPUT_PATH = ROOT / "_data" / "journals.yml"
OPENALEX_MAILTO = os.environ.get("OPENALEX_MAILTO", "ants.cnu@gmail.com")
USER_AGENT = f"cnu-ants-journal-sync/1.0 (mailto:{OPENALEX_MAILTO})"


class NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def dump_yaml(data, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Generated by scripts/sync_journals.py. Do not edit by hand.\n")
        yaml.dump(
            data,
            handle,
            Dumper=NoAliasDumper,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False,
            width=88,
        )


def fetch_bytes(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return response.read()
    except (urllib.error.URLError, TimeoutError, OSError):
        return subprocess.check_output(
            ["curl", "-fsSL", "-A", USER_AGENT, url],
            timeout=60,
        )


def fetch_openalex_source(issn: str):
    query = urllib.parse.urlencode({"mailto": OPENALEX_MAILTO})
    encoded_issn = urllib.parse.quote(issn)
    url = f"https://api.openalex.org/sources/issn:{encoded_issn}?{query}"
    try:
        raw = fetch_bytes(url)
    except subprocess.CalledProcessError:
        return None
    try:
        data = json.loads(raw.decode("utf-8"))
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict) or not data.get("id"):
        return None
    return data


def round_citedness(value):
    if value is None:
        return None
    try:
        return round(float(value), 1)
    except (TypeError, ValueError):
        return None


def build_journals(catalog):
    rows = []
    missing = []

    for item in catalog.get("journals") or []:
        issn = str(item.get("issn") or "").strip()
        title = item["title"]
        source = fetch_openalex_source(issn) if issn else None
        time.sleep(0.2)
        if source is None:
            missing.append(title)
            continue

        stats = source.get("summary_stats") or {}
        homepage = item.get("homepage") or source.get("homepage_url")
        openalex_id = source.get("id")
        rows.append(
            {
                "title": title,
                "name": source.get("display_name") or title,
                "issn": source.get("issn_l") or issn,
                "tags": item.get("tags") or [],
                "ccf": item.get("ccf"),
                "publisher": source.get("host_organization_name"),
                "homepage": homepage,
                "openalex": openalex_id,
                "citedness": round_citedness(
                    stats.get("2yr_mean_citedness")
                ),
                "h_index": stats.get("h_index"),
                "works_count": source.get("works_count"),
                "is_oa": source.get("is_oa"),
                "apc_usd": source.get("apc_usd"),
            }
        )

    rank_order = {"A": 0, "B": 1, "C": 2}
    rows.sort(
        key=lambda row: (
            rank_order.get(row.get("ccf"), 9),
            str(row["title"]),
        )
    )
    return rows, missing


def main():
    catalog = load_yaml(CATALOG_PATH)
    journals, missing = build_journals(catalog)

    if OUTPUT_PATH.exists():
        existing = load_yaml(OUTPUT_PATH) or {}
        if json.dumps(existing.get("journals"), sort_keys=True, default=str) == json.dumps(
            journals, sort_keys=True, default=str
        ) and existing.get("missing") == missing:
            print(
                json.dumps(
                    {
                        "changed": False,
                        "journals": len(journals),
                        "path": str(OUTPUT_PATH.relative_to(ROOT)),
                    },
                    ensure_ascii=False,
                )
            )
            return

    payload = {
        "source": "https://api.openalex.org/sources",
        "updated_at": dt.datetime.now(dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "missing": missing,
        "journals": journals,
    }
    dump_yaml(payload, OUTPUT_PATH)

    print(
        json.dumps(
            {
                "changed": True,
                "journals": len(journals),
                "missing": missing,
                "path": str(OUTPUT_PATH.relative_to(ROOT)),
            },
            ensure_ascii=False,
        )
    )
    if missing:
        sys.stderr.write(
            "Warning: not found in OpenAlex: " + ", ".join(missing) + "\n"
        )


if __name__ == "__main__":
    main()
